@startuml agi-wmts
component "avdpool import" as avdpool
component "Mapcache seeder" as wmts
component "QGIS server" as wms
database "PostgreSQL" as db
component "S3" as s3

avdpool--db : write
wms--db : read
wmts--wms : read
wmts--s3 : write
@enduml
